package common;

// Simülasyon boyunca gerçekleşen olayların enum listesi. EventLogger bu değerlerle log tutar.
public enum SimulationEvent {
    SIMULATION_STARTED, SIMULATION_PAUSED, SIMULATION_RESUMED,
    SIMULATION_RESET,   SIMULATION_COMPLETED,
    ROBOT_MOVED,        ROBOT_HIT_WALL,     ROBOT_HIT_OBSTACLE,
    CELL_CLEANED,       DIRT_ADDED,         OBSTACLE_ADDED,     OBSTACLE_REMOVED,
    BATTERY_LOW,        BATTERY_DEPLETED,   CHARGING_STARTED,   CHARGING_COMPLETED,
    RETURNING_TO_STATION, REACHED_STATION,
    ALGORITHM_CHANGED,  SPEED_CHANGED
}
